### ISSUE TITLE
 "threshold"?

### ISSUE THREAD

**Issue by philipeachille** [abbrcode/abbreviations-in-code#22]
any good suggestions for "threshold"?

**Comment by T1xx1** [comment]
Idk, maybe "thrhd".

**Comment by T1xx1** [comment]
Following [AllAcronyms](https://www.allacronyms.com/threshold/abbreviated) "threshold" is either abbreviated "Th" or "Thold". "Th" doesn't make any sense, it can also means "thread" or "theme". Idk about "Thold".

**Comment by kisvegabor** [comment]
Many years ago on oscilloscopes I saw "Th" but there everyone know what it from the context. Now I was checking some oscilloscope images and saw "Level" in most of the cases. 

For me "Th" could be ok with :yellow_circle: as it's highly context sensitive. E.g. it look good to me
```
void set_some_threshold(int th);
```

**Comment by philipeachille** [comment]
I deviate towards "thrsh" now. I tested it a bit in my code and this is the one I stumble the least over when reading it.

**Comment by kisvegabor** [comment]
> I deviate towards "thrsh" now.

It feel it hard to pronounce, write and remember. However, in the end we should find objective measures to decide which abbreviation to pick. We are different and what feels good for someone will feel strange for someone else.

**Comment by T1xx1** [comment]
Moved in [discussion](https://github.com/orgs/abbrcode/discussions/12)
