### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by T1xx1** [abbrcode/abbreviations-in-code#24]
The `CONTRIBUTING.md` has all the rules of this repo.

The index introduces some general concepts about abbrs for everyone and the `CONTRIBUTING.md` specific rules for the abbrs in this project.

We're adding new rules and making this repo bigger so I think it wouldn't be so bad to refactor the `CONTRIBUTING.md`.

What about restructuring the rules in these new sections?
- Whole list rules
- Single-line rules
- Single abbrs rules
- Context rules
- Others

**Comment by kisvegabor** [comment]
> We're adding new rules and making this repo bigger so I think it wouldn't be so bad to refactor the CONTRIBUTING.md.

I agree to scale that docs as the popularity of this repo grows.


I think the README should contain only very little information to not give the impression that these are all the rules. I mean:
- One paragraph of What it is? (Mainly the current "Goal" section)
- "Guide" roughly as it now + link to Contributing
- "List": as it is now
- "Index": not required as there will be only a few short sections
- "A good abbreviation is": not required, these should be in Contributing or partly in "What is it?"

In Contributing we can add all others you mentioned. But what are the "Context rules"?

**Comment by T1xx1** [comment]
> I think the README should contain only very little information to not give the impression that these are all the rules. I mean:
> - One paragraph of What it is? (Mainly the current "Goal" section)
> - "Guide" roughly as it now + link to Contributing
> - "List": as it is now
> - "Index": not required as there will be only a few short sections
> - "A good abbreviation is": not required, these should be in Contributing or partly in "What is it?"

I agree. We should change the current index with the section of the project with the section of the list like a b c d e etc... 
Move everything else to `CONTRIBUTING.md` or a new file called `Introduction`.. All rules must still goes to the `CONTRIBUTING.md`.

> In Contributing we can add all others you mentioned. But what are the "Context rules"?

Rules of how to write contexts or even which contexts are accepted if not all are valid.

**Comment by kisvegabor** [comment]
I wouldn't add more files. I think a README and a CONTRIBUTING should be fine. Do you plan to work on it. If not , I can add these changes too.

**Comment by T1xx1** [comment]
Yes I can do it. I'll wait a bit and start after the other PR. I have also other changes so I'm doing them all in one PR.

1- inline words order and indentation
2- we forgot about the topic of the JSON file, the generator and the website.
Should I open other issue or not?

**Comment by kisvegabor** [comment]
>  we forgot about the topic of the JSON file, the generator and the website.

For this please open a new issue.
