### ISSUE TITLE
JSON file, generator script and website

### ISSUE THREAD

**Issue by T1xx1** [abbrcode/abbreviations-in-code#25]
Just for info the genJson.pl doesn't work, the changes we have made since it was created don't fit anymore with the format it was used previously.

This issue is in standby.
- [x] #27
- [x] #19
- [x] #23
- [x] #14
- [x] #24
- [x] #26

_Originally posted by @kisvegabor in https://github.com/kisvegabor/abbreviations-in-code/issues/24#issuecomment-1386916491_

**Comment by philipeachille** [comment]
I'd wait for a bit longer to make new generators until this repo settles on its format

**Comment by T1xx1** [comment]
Yes, was already planned.

**Comment by oood** [comment]
I just issued it doesn't work, I would recommend removing the script (#44) until we are sure of the format the repository follows.

**Comment by kisvegabor** [comment]
Makes sense. Done here https://github.com/kisvegabor/abbreviations-in-code/commit/fab384e224e842fcdddc4bc705e18ed3faab2531
