### ISSUE TITLE
"lat" and "lng"

### ISSUE THREAD

**Issue by philipeachille** [abbrcode/abbreviations-in-code#28]
We should change the list to what Leaflet.js is using 

https://leafletjs.com/reference.html#latlng

**Comment by kisvegabor** [comment]
Are there other sources that suggest "lng" for "longitude"? E.g it's not listed here at all https://www.abbreviations.com/abbreviation/longitude

**Comment by T1xx1** [comment]
I prefer "long".

**Comment by philipeachille** [comment]
Leaflet, Mapbox, Google and I guess many others are using "lat, lng"

**Comment by kisvegabor** [comment]
I've search on it in Google like this: 
#### long: 40M results
![image](https://user-images.githubusercontent.com/7599318/213988996-c8d6e9dc-4270-4786-b28b-c86ad671ef0f.png)

#### lon: 5M results
![image](https://user-images.githubusercontent.com/7599318/213989174-e16a268a-9e8a-437a-a735-14dacf19beb6.png)

#### lng: 2M results
![image](https://user-images.githubusercontent.com/7599318/213989068-f88ea8b5-1e57-4457-b21d-4a68a4b788b4.png)

---

It suggests that "lng" is the least used.

**Comment by T1xx1** [comment]
I suggest add all of them with yellow for "lng" and "lon".

**Comment by kisvegabor** [comment]
MY suggestion about yellow was that there should be max 1 yellow to have clear suggestion.

**Comment by T1xx1** [comment]
Lol, sorry I meant red. Yellow are for those ones that have a context. They don't.

**Comment by philipeachille** [comment]
I really still suggest to use "lat" and "lng", both green, and ignore all other options.

This is a Google Places API response: 

"geometry":
        {
          "location": { "lat": -33.866489, "lng": 151.1958561 },

Plus, as I said, leaflet.js and mapbox - probably the largest mapping libraries - use these also.

**Comment by kisvegabor** [comment]
I'm open to it, if we find enough evidence for that it's the most standard. But let's discuss the new words once the refactoring is finished.

**Comment by T1xx1** [comment]
Should I start refactoring the code?

**Comment by philipeachille** [comment]
yea, first refactor and then do 1 issue, followed by one 1 pr per abbrev

**Comment by kisvegabor** [comment]
Which code do you mean? :slightly_smiling_face: 

I meant refactoring the README to reflect the new ideas and plans.

**Comment by T1xx1** [comment]
Isn't a markdown file a non-executable type of code?

**Comment by kisvegabor** [comment]
> Isn't a markdown file a non-executable type of code?

It can be, I guess :slightly_smiling_face: I wasn't sure what you mean by code. (it could refer to the pearl script too)

**Comment by T1xx1** [comment]
No, that's part of #25.

**Comment by T1xx1** [comment]
Moved to [discussions](https://github.com/orgs/abbrcode/discussions/14)
