### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by T1xx1** [abbrcode/abbreviations-in-code#34]
# ➕ New abbr

## Criteria

- Not an acronym (e.g. **RAM, CPU, SQL**) or a conventions (e.g. **i, j, k**).
- Lowercase
- Singular and neutral form.
- Max 1 🟢 abbr

<br>

### Commercial • 🟢 com

<br>

## Pros
- 

## Cons
- 

<br>

---

- [x] I can handle the following pr related to this issue to add the new abbr.

**Comment by kisvegabor** [comment]
I'm ok with "org" but we should discuss "com". Now we have these:

![image](https://user-images.githubusercontent.com/7599318/220088038-ea412f3c-bc30-4c7d-9b6c-5378db59238e.png)

"com" is a good abbreviation (also used in Windows for COM ports) and I don't think we should use it for "Commercial"  which is not likely to be used in codes.

To make a decision I think we should find abbreviations for "common" and "communication" too.

**Comment by T1xx1** [comment]
Ok for org.

I didn't even notice that commercial was already on the list, my bad. I put it in here because I thought it was missing. Btw why is it red rn?

But you pointed out that these 3 words have the same abbr though they are very different words. So I have these suggestions.

- commercial • com (leave it like that bc of URLs and make it green)
- common • comm (like different diff or current curr)
- communication • ? (idk)

**Comment by kisvegabor** [comment]
My suggestion would be
- commercial • :yellow_circle: com { ??? }      (in some contexts it's fine)
- communication • :green_circle: com            (most common in programming so it should be abbreviated)
- common • :red_circle: com • :red_circle: comm      (it's not that long, having it as "common" should be ok too)

**Comment by kisvegabor** [comment]
> commercial • yellow_circle com { URLs }

Sounds good to me!

**Comment by philipeachille** [comment]
With this I would also want to suggest that we keep double letters: "comm". I noticed this in my coding using "col" and "coll" and decided that keeping double letters can avoid conflict with other abbrevs

**Comment by T1xx1** [comment]
Double letters are allowed and there are a few in the list but they are marked with red as they can be easily get confused with other abbrs.
