### ISSUE TITLE
Controller

### ISSUE THREAD

**Issue by T1xx1** [abbrcode/abbreviations-in-code#35]
# ➕ New abbr

## Criteria

- Not an acronym (e.g. **RAM, CPU, SQL**) or a conventions (e.g. **i, j, k**).
- Lowercase
- Singular and neutral form.
- Max 1 🟢 abbr

<br>

### Controller • ?

<br>

## Pros
- In the list, there's microcontroller.

## Cons
- 

<br>

---

- [x] I can handle the following pr related to this issue to add the new abbr.

**Comment by kisvegabor** [comment]
In web development is there a good abbreviation e.g. in case of a Model-View-Controller system?

**Comment by T1xx1** [comment]
Idk.

**Comment by T1xx1** [comment]
Moved to [discussions](https://github.com/orgs/abbrcode/discussions/15)
