### ISSUE TITLE
Request: switch license

### ISSUE THREAD

**Issue by oood** [abbrcode/abbreviations-in-code#45]
**Rationale:**

The current MIT license in use is generally only for software, and the main part of this project is documentation, so a more appropriate license is needed.

**Suggestion:**

Use [CC](https://creativecommons.org/licenses/) or [GFDL](https://www.gnu.org/licenses/fdl-1.3.en.html) license.

But in my personal opinion, since this project is about documenting facts rather than creating new things, it could be done under a more open license that makes it easy for people to use, like **public domain**. so when people copy parts of a document, they don't need to credit who the author is or include a license in context.

This issue is a fork of a previous thread (#41), you may be interested in reading the previous discussion history.

**Comment by T1xx1** [comment]
https://choosealicense.com/non-software/

**Comment by oood** [comment]
> https://choosealicense.com/non-software/

Personally, I would recommend [CC0](https://creativecommons.org/publicdomain/zero/1.0/). This releases the document into the public domain or disclaims copyright to the fullest extent permitted by law.

The reason is that this will be a dictionary where most of the content is consensus and not original, CC0 is good for documenting facts and is easy to use, licenses like CC-BY require attribution to the author or citation to the original source, this makes it difficult to freely use the documentation.

But CC0 is not compatible with Wikipedia, because Wikipedia uses the stricter CC-BY-SA 3.0, which will prevent us from directly importing the list. But since this is a dictionary, no one can claim copyright on a word, so maybe we can just copy it? idk.

**Comment by kisvegabor** [comment]
> But in my personal opinion, since this project is about documenting facts rather than creating new things

I'm not sure what "fact" means in this context. For example "sw" is a recommended abbreviation of "software". Is it fact? I'd rather say it's an opinion.
 
> The reason is that this will be a dictionary where most of the content is consensus and not original [...]

I sounds better to me.

---

I know only the basic open source software licenses so I can't really decide which option would be the best, however CC0 really sounds like what we need.

If you all agree with it, I'll change the license.

**Comment by oood** [comment]
> I'm not sure what "fact" means in this context. For example "sw" is a recommended abbreviation of "software". Is it fact? I'd rather say it's an opinion.

When there is a consensus, I would call it a fact, and dictionaries are not for coining new words, but for documenting the consensus.

> however CC0 really sounds like what we need.


The benefit of CC0 is that other projects or anyone in the world can use this project completely freely, but the challenge for us is that we cannot copy content from Wikipedia, Wiktionary or other copyrights, unless different content is given different license.

[CC-BY](https://creativecommons.org/licenses/by/3.0/) is the documentation license equivalent to the current MIT license, but this is still too broad for Wikipedia's CC-BY-SA, so even with CC-BY, we don't allow importing content from Wikipedia.

If you plan to import content from Wikipedia, it must be licensed under the same license as Wikipedia, which is [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/).

**Comment by kisvegabor** [comment]
> [CC-BY](https://creativecommons.org/licenses/by/3.0/) is the documentation license equivalent to the current MIT license, but this is still too broad for Wikipedia's CC-BY-SA, so even with CC-BY, we don't allow importing content from Wikipedia.

Clear now, thank you. Let's see what will be conclusion in #47 and make decision accordingly.

**Comment by oood** [comment]
> Clear now, thank you. Let's see what will be conclusion in #47 and make decision accordingly.

Also, if other members of the project previously contributed parts licensed under MIT, switching licenses requires their approval, or rewriting that part.

But since this is a dictionary, I don't know how to rewrite a word. 🤣

**Comment by oood** [comment]
Hey guys.

We are talking about switching the license of this project, since you are a contributor to this project, I hope you can join our discussion.

Because your contribution is licensed under the MIT license, switching licenses requires your consent, or we need to rewrite the part you contributed.

In addition, we are making a series of major changes to the project, here are some topics:

> Initial discussion #41
> Request: switch license #45
> Request: make this project a dictionary #46
> Request: Make the project more inclusive and accessible #47
> Request: translate this project #48
> Request: move project under an organization #49

Let's build this project together.

@yan-kuan @h-h-h-h @cfjello @philipeachille @stevencychuang @Firemanarg @chriscalo @Ramesh-X @emareg @SharifElfouly

**Comment by chriscalo** [comment]
Consent from me is granted to change the license to whatever you feel is best for the project. Let me know if you need my consent phrased in any particular way or recorded anywhere specific (other than here).

**Comment by cfjello** [comment]
Consent from me is granted to change the license to whatever you feel is
best for the project. Let me know if you need my consent phrased in any
particular way or recorded anywhere specific (other than here). On Sun, 5
Mar 2023 at 00.47, oood ***@***.***> wrote:

Hey guys.

**Comment by oood** [comment]
Hi, everyone, we are still discussing the license that the project will adopt in the future.

A more permissive license than MIT is expected to be adopted, CC0 is my recommendation as the proponent of changing the license, this will put the project directly under the public domain, so everyone can use the project completely freely.

But there are some other options out there too, like CC-BY, CC-BY-SA, GFDL licenses.

It would be very helpful if you would like to join the discussion. You can reply to this thread with the license you want to use, and we will choose a new license in the future based on the preferences of everyone in this thread.

I may @ you twice in the future, the first time is about consensus generation. The second time is to ask you to confirm the new license.

We look forward to your joining us to build a better project, thank you for your contribution.

@yan-kuan @h-h-h-h @cfjello @philipeachille @stevencychuang @Firemanarg @chriscalo @Ramesh-X @emareg @SharifElfouly

**Comment by philipeachille** [comment]
CC0 is fine with me.

**Comment by oood** [comment]
> CC0 is fine with me.

It is worth pointing out that
Some differences between CC0 and the current MIT license are:

**MIT requires attribution to the project author(s) and includes a copy of the license each time the project is used.**

**CC0 has no requirements.**

**MIT licensees can change the license and even close source it.**

**CC0 is irrevocable, which means it will be shared forever as the shared knowledge of humanity.**



In addition, the CC-BY license is almost a document license equivalent to the MIT license, which requires attribution by the user like MIT, except that it is also irrevocable. It is worth noting that bylined authors can have a positive impact on promoting a project.

**Comment by h-h-h-h** [comment]
> CC0 is fine with me.

Same. Choose whatever. I thought this would be possible with MIT anyway - taking the work and relicensing it.

**Comment by oood** [comment]
> maybe one can license the planned JSON file as CC0 and any other works derived from that with CC-BY-SA

sounds cool. Since that's CC0, anyone can use it in any way, including a more restrictive license.

**Comment by T1xx1** [comment]
I didn't follow this issue very well, so what was the final decision?

**Comment by T1xx1** [comment]
The list is open source and as such MIT is the best
