### ISSUE TITLE
Request: make this project a dictionary

### ISSUE THREAD

**Issue by oood** [abbrcode/abbreviations-in-code#46]
**Rationale:**

Programming is full of abbreviations, and for non-native English speakers or beginners in programming, there is rarely a complete dictionary on the Internet for them to understand common abbreviations.

This project has the potential and foundation to be a dictionary, we just need to make more of it.

**Suggestions:**

- First: We shouldn't be limited to abbreviations, acronyms should be covered as well.

- Second: There is already a list of acronyms on Wikipedia, and if the #45 license issue is resolved, we can extend our project with existing words on Wikipedia.

- Third: Make the whole project a wiki project that everyone can contribute to, because the language is from the people, by the people, for the people.

This issue is a fork of a previous thread (#41), you may be interested in reading the previous discussion history.

**Comment by kisvegabor** [comment]
> There is already a list of acronyms on Wikipedia

Could you link that Wikipedia page to see many new entries would adding acronyms mean?

> Make the whole project a wiki project that everyone can contribute to [...]

Unlike Wikipedia, this repo is opinion based to some extent. I'm afraid without a maintainer we will end up having inconsistent content.

**Comment by oood** [comment]
> Could you link that Wikipedia page to see many new entries would adding acronyms mean?

Sorry, I forgot to link, here is https://en.wikipedia.org/wiki/List_of_computing_and_IT_abbreviations

> Unlike Wikipedia, this repo is opinion based to some extent. I'm afraid without a maintainer we will end up having inconsistent content.

You are right, the purpose of a wiki is to increase user engagement.

But I realize this may not be an accurate representation of whether an abbreviation is actually popular to a certain extent.

I noticed that there are many internet slang/acronym dictionaries on the internet, [take this](https://www.urbandictionary.com/define.php?term=db) as an example, a `db` will have multiple different interpretations, where ranking is based on user votes.

I think this is very good, but I don't know how to implement it in github.

We need to achieve two things:

First: Increase user engagement, including making it easier to contribute new abbreviation or explanations of existing abbreviation.

Second: Display user votes for each abbreviation.

Remember the `referral` in http? It's a typo, but it has been accepted because of consensus.

A voting system can help generate consensus.

**Comment by T1xx1** [comment]
> I noticed that there are many internet slang/acronym dictionaries on the internet, [take this](https://www.urbandictionary.com/define.php?term=db) as an example, a `db` will have multiple different interpretations, where ranking is based on user votes.

The urban dictionary is not that such reliable source.

**Comment by kisvegabor** [comment]
To be honest I haven't been thinking about this highly consensus based same system. I have a conventional open-source software developer background and I could imagine only the "open and issue or PR if you would like to contribute" approach.

The main problem I see with a voting system is that there is no filtering. Anyone can up vote anything regardless how deeply they have considered that vote. E.g. any novice developer can vote for something, and this vote will be worth the same as a senior developer's vote. So in the end end the ratio of beginners vs. seniors will determine the quality of the list. 

The "open an issue/PR" approach helps to filter out the non serious ideas as we can make changes only if some evidence is shown about the proposed word is better than the current one.

**Comment by kisvegabor** [comment]
> Sorry, I forgot to link, here is https://en.wikipedia.org/wiki/List_of_computing_and_IT_abbreviations

Thank you! However I think we shouldn't integrate this list for various reasons:
- Potential licensing issues of using content from Wikipedia
- It'd be a duplicated content -> maintenance burden
- There are much more acronyms than abbreviations (as I foresee at least). I'm afraid it'd be hard to find the  abbreviations among the many acronyms

I think it'd be better to link this Wikipedia page as "For the list of acronyms visit this Wikipeda page".

**Comment by oood** [comment]
@T1xx1 @kisvegabor 

How about that, we continue with the current model, using issue templates to let people submit abbrs, because issue templates can be voted on, because there are emojis.

The change that was made is that each abbr is connected to an issue so people can see the history of previous discussions and vote on them.

an example:

> - standard input output • 🟢 [stdio](https://github.com/kisvegabor/abbreviations-in-code/issues/37)

**Comment by oood** [comment]
> The urban dictionary is not that such reliable source.

Agreed with this, but I like their voting system.

**Comment by oood** [comment]
> However I think we shouldn't integrate this list for various reasons:

As discussed earlier, I wanted this project to be a complete dictionary for newcomers and non-native English speakers so that they don't have to go to a second site to see other parts.

As to whether there would be a licensing issue with the Wikipedia word, if we rewrite then there shouldn't be a licensing issue.

You can see that there is nothing original in that Wikipedia list, just words.


So, if we add more content on a per-word basis, including context, explanation, then we are not considered plagiarized from Wikipedia.

They cannot claim copyright to an abbreviation like `db`.

**Comment by kisvegabor** [comment]
> The change that was made is that each abbr is connected to an issue so people can see the history of previous discussions and vote on them.

We will have ~200 issues but it's okay if it's consistent.

> As to whether there would be a licensing issue with the Wikipedia word, if we rewrite then there shouldn't be a licensing issue.

It's great if it's not an issue. What about the other two concerns?
> - It'd be a duplicated content -> maintenance burden
- There are much more acronyms than abbreviations (as I foresee at least). I'm afraid it'd be hard to find the abbreviations among the many acronyms

**Comment by T1xx1** [comment]
> @T1xx1 @kisvegabor 
> 
> How about this, we continue with the current method, using issue templates to let people submit abbrs, because issue templates can be voted on, because there are emojis.
> 
> The change that was made is that each abbr is connected to an issue so people can see the history of previous discussions and vote on them.
> 
> an example:
> 
> > - standard input output • 🟢 [stdio](https://github.com/kisvegabor/abbreviations-in-code/issues/37)
> 
> 
> But don't use a PR unless fix a typo, as it will be hard to have a record of the discussion.

This method seems to messy and complicated. When I said to you that I didn't like the discussions way it was because I thought you wanted to move everything in the discussion section.
What about.
When someone suggest a new abbr it's made via issues with the templates. We discuss a little under it and when agreed we add the abbr, close the issue and in the same time we open a new discussion with the abbr in it, referring this discussion in the abbr in README like you shown. In this way we don't have 200 issue as @kisvegabor pointed out still having a place to discuss the abbr.

**Comment by oood** [comment]
> It'd be a duplicated content -> maintenance burden
> > There are much more acronyms than abbreviations (as I foresee at least). 

Yes, that would be an endless list, **but we need to make a rule to ensure that we only record common and well-known acronyms**, such as `db`, `http`, this project aims to help those who are new to programming and non Native English speakers, so if we exclude words like db, they have to go to another site to find it.

Of course, it's not necessary to cover acronyms like `HGDCFUDFS` that most people don't know (which, by the way, doesn't exist, I just made it up myself). 🤣

> I'm afraid it'd be hard to find the abbreviations among the many acronyms

Two things I recommended earlier can help improve:

[The first is sorted alphabetically](https://github.com/kisvegabor/abbreviations-in-code/issues/48#issuecomment-1455109270), one file per letter, we just need to link to correct files in the main readme file.

````
abbreviations-in-code
├─── readme.md
├─── en-US
|	├─── A.md
|	├─── B.md
|	├─── ...
|	└─── Z.md
├─── it-IT
|	├─── A.md
|	├─── ...
|	├─── Z.md
|	└─── readme.md
├─── raw
|	└─── raw
└─── docs
````

The second is to sort by abbreviations.

like:
```
db, database
db, debug
```

**Comment by oood** [comment]
> because I thought you wanted to move everything in the discussion section.

Sorry, my thoughts are constantly adjusted according to the actual situation. It changes every day, lol.

> 
What about.
When someone suggest a new abbr it's made via issues with the templates. We discuss a little under it and when agreed we add the abbr, close the issue and in the same time we open a new discussion with the abbr in it, referring this discussion in the abbr in README like you shown. In this way we don't have 200 issue as @kisvegabor pointed out still having a place to discuss the abbr.

That's great, I hope this! and I like the idea. So open issues are just for new abbreviations, and closed issues are archives of old discussions. 

Also, I don't think we have to open an issue for an old abbreviation that hasn't created a discussion yet, which would be a hassle, we can create a link to encourage others to create an issue discussion.

**Comment by T1xx1** [comment]
> > because I thought you wanted to move everything in the discussion section.
> 
> Sorry, my thoughts are constantly adjusted according to the actual situation. It changes every day, lol.

Don't worry. At the end it counts what we build.


> > What about.
> > When someone suggest a new abbr it's made via issues with the templates. We discuss a little under it and when agreed we add the abbr, close the issue and in the same time we open a new discussion with the abbr in it, referring this discussion in the abbr in README like you shown. In this way we don't have 200 issue as @kisvegabor pointed out still having a place to discuss the abbr.
> 
> That's great, I hope this! and I like the idea. So open issues are just for new abbreviations, and closed issues are archives of old discussions.

Yes. So this method will also not waste my templates HAHAH. I will still remove the "editAbbr.md" as we will use the discussions.
If it's not a problem for you I would like to do the "translateLang.md" template.
 
> Also, I don't think we have to open an issue for an old abbreviation that hasn't created a discussion yet, which would be a hassle, we can create a link to encourage others to create an issue discussion.
> 

Exactly.

**Comment by T1xx1** [comment]
> ````
> abbreviations-in-code
> ├─── readme.md
> ├─── en-US
> |	├─── A.md
> |	├─── B.md
> |	├─── ...
> |	└─── Z.md
> ├─── it-IT
> |	├─── A.md
> |	├─── ...
> |	├─── Z.md
> |	└─── readme.md
> ├─── raw
> |	└─── raw
> └─── docs
> ````

It would not imply having 26 files for each lang. After making the db and the script for the en I want to request the it. The file will be 52 not counting the index, scripts and any type it's not a list. You will also need a separate file for the lang index. 
If we use headers and paragraph we should be able to keep list sorted alphabetical without creating 34959 files. In each one we will format an index like in the curr README so is easy to navigate also on long lists.


Abbr in code
- db
	- abbr.json
	- meta.json
- scripts
	- builder (idk how to call this thing)
- lang
	- en.md
	- it.md
- readme.md

So we mantain abbrs.json and everything should be ok.
Also suggest to have package.json without having dependencies. Npm is useful for because you can exe script easily.

**Comment by oood** [comment]
> Yes. So this method will also not waste my templates HAHAH. I will still remove the "editAbbr.md" as we will use the discussions.
> If it's not a problem for you I would like to do the "translateLang.md" template.

No problem, and I hope I can help too.

Also templates allow comments, which are not visible in the final issue, but are visible to people creating new issue, maybe we can introduce that functionality to explain the format to people.

And make the final issue look uniform in format.

I remember seeing this in a project before and I needed to find out how to do it because I forgot.


>  If we use headers and paragraph we should be able to keep list sorted alphabetical without creating 34959 files. In each one we will format an index like in the curr README so is easy to navigate also on long lists.

You are right. 

Also, if we import [that Wikipedia list](https://en.wikipedia.org/wiki/List_of_computing_and_IT_abbreviations), (I haven't counted), but it looks like there are at least 1,000 unique new acronyms.
How do we deal with it?


>  So we mantain abbrs.json and everything should be ok.
> Also suggest to have package.json without having dependencies. Npm is useful for because you can exe script easily.


It does look easier to use. and I'm assuming English abbreviations + acronyms are no more than 5000 words in total, so perhaps putting them in one file would work.

**Comment by T1xx1** [comment]
> It does look easier to use. and I'm assuming English abbreviations + acronyms are no more than 5000 words in total, so perhaps putting them in one file would work.
> 

In any case we can change it after. Right now we need to test if works or not.

**Comment by oood** [comment]
> In any case we can change it after. Right now we need to test if works or not.

Yes! let's do it.

**Comment by philipeachille** [comment]
I am not sure whether this project is the same as that Wikipedia list ?

**Comment by oood** [comment]
> I am not sure whether this project is the same as that Wikipedia list ?

No, Wikipedia is just an acronym. We'll focus on being a dictionary, potentially larger than Wikipedia in the future, and that includes multiple languages, contexts of words, multiple formats, and even future IDEs may embed our dictionaries to suggest names as you type.

So, this is definitely not just another Wikipedia.

**Comment by philipeachille** [comment]
But why bring in all that stuff from that wikipedia entry?

**Comment by T1xx1** [comment]
>... and even future IDEs may embed our dictionaries to suggest names as you type.

One of my projects was actually a vs code extension that could provide suggestion on words of their abbrs.
Apart the fact that I like this project that's also why I'm so active on this repo.

**Comment by oood** [comment]
> But why bring in all that stuff from that wikipedia entry?
> e.g. ARPANET does not belong into this repo I think, and there are many many more of this kind

In my opinion we need to do these things:

Choose an organization name > formulate our goals > formulate our inclusion standards > formulate our format standards > improve the dictionary.

Importing to Wikipedia is just one possible move to improve the dictionary, but there are inclusion criteria there before then, so I'm not worried about some abbreviations being added that shouldn't exist in this project.


Before that, the goal still needs to be determined, because the dictionary is only a potential possibility, and further discussion is needed in the future.

>  BTW I could not implement these abbrs as there no remote method to retrieve them.

It is hoped that a format that can be generated for your expansion will be adopted after the database is complete.

**Comment by T1xx1** [comment]
> >  BTW I could not implement these abbrs as there no remote method to retrieve them.
> 
> It is hoped that a format that can be generated for your expansion will be adopted after the database is complete.

Hope so. Maybe an other related project could be an API.

**Comment by kisvegabor** [comment]
Let figure out what to do with the acronyms because I think some other things are depending on this decision.

My opinion is the we should **not** include the acronyms because:
1. there is no added value: RAM means Random Access Memory, it's a fact, you can find in google or Wikipedia what it means
2. it's a maintenance burden to constantly  update from Wikipedia
3. acronyms will greatly outnumber the abbreviations so what really has an added value will be harder to find
4. acronyms needs to be handled differently: 
   - no translation  (doesn't make sense to translate Random Access Memory)
   - no linked issue (no discussion needed as it's a fact)
   - no level of recommendation (RAM mean Random Access Memory, it's always recommended)

**Comment by T1xx1** [comment]
> Let figure out what to do with the acronyms because I think some other things are depending on this decision.
> 
> My opinion is the we should **not** include the acronyms because:
> 1. there is no added value: RAM means Random Access Memory, it's a fact, you can find in google or Wikipedia what it means
> 2. it's a maintenance burden to constantly  update from Wikipedia
> 3. acronyms will greatly outnumber the abbreviations so what really has an added value will be harder to find
> 4. acronyms needs to be handled differently: 
>    - no translation  (doesn't make sense to translate Random Access Memory)
>    - no linked issue (no discussion needed as it's a fact)
>    - no level of recommendation (RAM mean Random Access Memory, it's always recommended) 

Another thing that comes to my mind is that acronyms are acronyms and abbrs are abbrs. I don't see the point of mixing them.

**Comment by oood** [comment]
> > Let figure out what to do with the acronyms because I think some other things are depending on this decision.
> > My opinion is the we should **not** include the acronyms because:
> > 
> > 1. there is no added value: RAM means Random Access Memory, it's a fact, you can find in google or Wikipedia what it means
> > 2. it's a maintenance burden to constantly  update from Wikipedia
> > 3. acronyms will greatly outnumber the abbreviations so what really has an added value will be harder to find
> > 4. acronyms needs to be handled differently:
> >    
> >    * no translation  (doesn't make sense to translate Random Access Memory)
> >    * no linked issue (no discussion needed as it's a fact)
> >    * no level of recommendation (RAM mean Random Access Memory, it's always recommended)
> 
> Another thing that comes to my mind is that acronyms are acronyms and abbrs are abbrs. I don't see the point of mixing them.

Yes, maybe in two documents.

**Comment by T1xx1** [comment]
> So maybe two docs would be good for them? Or start a separate project in that organization that works for acronyms?

I prefer this solution.

**Comment by oood** [comment]
> I prefer this solution.

Yes, we can have two different repositories under the same org, I like that, easy to find!

And it can be managed centrally, and the same collection rules and issue templates can be formulated to reduce the maintenance burden.

**Comment by T1xx1** [comment]
Yep, rules, formats, and goals are of the org among all projects. There will be also native project tasks and others but referred as development of the org itself.

**Comment by philipeachille** [comment]
> Or start a separate project in that organization that works for acronyms?

If anything than this. I personally would not maintain this though. I am only interested in creating a clear reference for abbreviations that are used for variable naming

**Comment by T1xx1** [comment]
> > Or start a separate project in that organization that works for acronyms?
> 
> If anything than this. I personally would not maintain this though. I am only interested in creating a clear reference for abbreviations that are used for variable naming

So it will be better to have them separate so you have to mantain a repo without having to seek in the code if their are mixed for the abbrs only.

**Comment by philipeachille** [comment]
Then the org name can not include "abbr", if the org attempts to also list "acro" - which I thoroughly believe it should NOT.

**Comment by T1xx1** [comment]
Got it.

**Comment by oood** [comment]
I see, why not join the organization? @philipeachille

**Comment by philipeachille** [comment]
how do i join the organization?

**Comment by oood** [comment]
> how do i join the organization?

@T1xx1 @kisvegabor

How to invite?

**Comment by oood** [comment]
> how do i join the organization?

@T1xx1 @kisvegabor

How to invite?

**Comment by T1xx1** [comment]
Wait

**Comment by T1xx1** [comment]
Sent

**Comment by philipeachille** [comment]
btw, i think "abbrcodes" is somewhat wrong, because code is not plural, the abbreviations are plural

**Comment by T1xx1** [comment]
It stands for "abbreviate codes"

**Comment by oood** [comment]
> btw, i think "abbrcodes" is somewhat wrong, because code is not plural, the abbreviations are plural

makes sense.

🤔 `abbrscode`? But in this case you need `abbrsincode`, or just `abbre` (that name is available) ?

**Comment by philipeachille** [comment]
"abbres" ? 🤔 ... i still prefer "abbrcode"

**Comment by oood** [comment]
Can we open a new discussion about names?

@T1xx1  @philipeachille  


There is no link to the discussion yet in brevis.

> Want to discuss it?
> Open a discussion here: https://github.com/abbrcodes/discussions/discussions

**Comment by T1xx1** [comment]
> Can we open a new discussion about names? 

There is 4
