### ISSUE TITLE
Edit: tmp/temp

### ISSUE THREAD

**Issue by emareg** [abbrcode/abbreviations-in-code#60]
# ✏️ Edit curr abbr

## Which abbrs do you want to modify?

-> tmp and temp

## What do you want to change?

-> Switching them as `tmp` should be temporary. The reason is that Unix/Linux uses `tmp` for temporary files so `tmp=temporary` should be more intuitive for most developers.

---

-  [x] I can handle the following pr related to this issue to edit the abbrs.

**Comment by T1xx1** [comment]
Looking it up online temp seems the most used

![image](https://github.com/abbrcode/abbreviations-in-code/assets/69322987/a952cf53-83a1-49ec-8def-db3af6c2264c)

Btw tmp is used for `temperature` which I don't understand in any context how that should be a programming/software term so I'm going to remove it and assign both `temp` and `tmp` to temporary
