### ISSUE TITLE
Suggestion for Container

### ISSUE THREAD

**Issue by edulourenzo** [abbrcode/abbreviations-in-code#64]
# ➕ Container

<br>

### _container_
- 🟡 _cntr_ { _web_ }

<br>

## Pros
- 

## Cons
- Center
- Control
- Counter

<br>

---

**Comment by T1xx1** [comment]
Hi @edulourenzo.

It seems fair to me also searching it online pops up.

I think there are no cons as center doesn't have an abbr, control -> ctrl and counter I think could be count.

**Comment by T1xx1** [comment]
Added [Commit](https://github.com/abbrcode/abbreviations-in-code/commit/fe96336806441bb8eb627db493807067e9ce09c8).

Thank you!
