### ISSUE TITLE
yellow {reference} naming consistency

### ISSUE THREAD

**Issue by valteu** [abbrcode/abbreviations-in-code#65]
# ✏️ Edit curr abbr

## Which abbrs do you want to modify?

-> - no • 🟡 n { only with **yes** }

## What do you want to change?

-> I think having just the 'y' as reference is more consistent:
- no • 🟡 n { only with **y** }

---

-  [x] I can handle the following pr related to this issue to edit the abbrs.

**Comment by T1xx1** [comment]
You're right. Also because in yes says n
![Screenshot (8)](https://github.com/abbrcode/abbreviations-in-code/assets/69322987/06354ba0-ea08-4936-b251-dc1ec0e98acc)

**Comment by T1xx1** [comment]
https://github.com/abbrcode/abbreviations-in-code/commit/c211741a7c1369e9f7779f890926848e0e2ae18c
