### ISSUE TITLE
`fd` refers to file *descriptors*

### ISSUE THREAD

**Issue by nicholaswmin** [abbrcode/abbreviations-in-code#67]
Edit `fd`

## What do you want to change?

-> just the description itself; it's [file *descriptors*][fd], not description. it doesn't have to do with files in the general sense, at all.

---

-  PR: https://github.com/abbrcode/abbreviations-in-code/pull/66

[fd]: https://en.wikipedia.org/wiki/File_descriptor

**Comment by T1xx1** [comment]
#66
